(in-package :cosmos-db)
(alexandria:define-constant +header-authorization+ "Authorization" :test #'string=)
(alexandria:define-constant +header-content-type+ "Content-Type" :test #'string=)
(alexandria:define-constant +header-if-match+ "If-Match" :test #'string=)
(alexandria:define-constant +header-if-none-match+ "If-None-Match" :test #'string=)
(alexandria:define-constant +header-if-modified-since+ "If-Modified-Since" :test #'string=)
(alexandria:define-constant +header-user-agent+ "User-Agent" :test #'string=)
(alexandria:define-constant +header-activity-id+ "x-ms-activity-id" :test #'string=)
(alexandria:define-constant +header-consistency-level+ "x-ms-consistency-level" :test #'string=)
(alexandria:define-constant +header-continuation+ "x-ms-continuation" :test #'string=)
(alexandria:define-constant +header-date+ "x-ms-date" :test #'string=)
(alexandria:define-constant +header-max-item-count+ "x-ms-max-item-count" :test #'string=)
(alexandria:define-constant +header-partition-key+ "x-ms-documentdb-partitionkey" :test #'string=)
(alexandria:define-constant +header-enable-cross-partition+ "x-ms-documentdb-query-enablecrosspartition" :test #'string=)
(alexandria:define-constant +header-session-token+ "x-ms-session-token" :test #'string=)
(alexandria:define-constant +header-version+ "x-ms-version" :test #'string=)
(alexandria:define-constant +header-a-im+ "A-IM" :test #'string=)
(alexandria:define-constant +header-partition-key-range-id+ "x-ms-documentdb-partitionkeyrangeid" :test #'string=)
(alexandria:define-constant +header-allow-tentative-writes+ "x-ms-cosmos-allow-tentative-writes" :test #'string=)
;; Define constants for header names
(alexandria:define-constant +header-is-query+ "x-ms-documentdb-isquery" :test #'string=)
;; Define constants for content types
(alexandria:define-constant +content-type-query-json+ "application/query+json" :test #'string=)
(alexandria:define-constant +content-type-json+ "application/json" :test #'string=)
;; create document header
(alexandria:define-constant +header-is-upsert+ "x-ms-documentdb-is-upsert" :test #'string=)
(alexandria:define-constant +header-indexing-directive+ "x-ms-indexing-directive" :test #'string=)
;;delete document header
(alexandria:define-constant +header-request-charge+ "x-ms-request-charge" :test #'string=)
;;collections / containers
(alexandria:define-constant +header-offer-throughput+ "x-ms-offer-throughput" :test #'string=)
(alexandria:define-constant +header-offer-autopilot+ "x-ms-cosmos-offer-autopilot-settings" :test #'string=)
